#ifndef __BOARDCFG_H__
#define __BOARDCFG_H__

#include "hi_unf_demux.h"
#include "hi_unf_frontend.h"
#include "hi_adp_ini.h"


#ifdef __cplusplus
extern "C" {
#endif

#ifndef HI_TUNER_NUMBER
#define HI_TUNER_NUMBER         8
#endif

#ifdef ANDROID
#define FRONTEND_CONFIG_PATH  "/system/lib/"
#else
#define FRONTEND_CONFIG_PATH  "/usr/local/cfg/"
#endif
#define FRONTEND_CONFIG_FILE  FRONTEND_CONFIG_PATH "frontend_config.ini"
#define TUNERNUM_SECTION      "tunernum"
#define SECTION_MAX_LENGTH    (64)

#define USE_I2C      (0)
#define NOT_MODIFY   (0)
#define NEED_RESET   (1)
#define USER_DEFINED (1)

/* The default value when read failed. */
#define DEFAULT_TUNER_NUM        (1)
#define DEFAULT_SIG_TYPE         (HI_UNF_TUNER_SIG_TYPE_CAB)

/* Tuner and Demod device and info. */
#define DEFAULT_TUNER_TYPE        (HI_UNF_TUNER_DEV_TYPE_TDA18250B)
#define DEFAULT_TUNER_ADDR        (0xc0)
#define DEFAULT_DEMOD_TYPE        (HI_UNF_DEMOD_DEV_TYPE_3130E)
#define DEFAULT_DEMOD_ADDR        (0xa0)
#define DEFAULT_DEMOD_OUTPUT_MODE (HI_UNF_TUNER_OUTPUT_MODE_SERIAL)
#define DEFAULT_DEMOD_RST_TYPE    (NEED_RESET)
#define DEFAULT_DEMOD_RST_GPIO    (0)
#define DEFAULT_MEMORY_MODE       (0)

/* I2C */
#define DEFAULT_I2C_TYPE          (USE_I2C)
#define DEFAULT_I2C_CHNUM         (1)
#define DEFAULT_GPIOI2C_SCL       (0)
#define DEFAULT_GPIOI2C_SDA       (0)

/* TSOUT  */
#define DEFAULT_DEMOD_TSOUT_MODE    (NOT_MODIFY)
#define DEFAULT_DEMOD_OUTPUT_TSDAT0 (HI_UNF_TUNER_OUTPUT_TSDAT0)
#define DEFAULT_DEMOD_OUTPUT_TSDAT1 (HI_UNF_TUNER_OUTPUT_TSDAT1)
#define DEFAULT_DEMOD_OUTPUT_TSDAT2 (HI_UNF_TUNER_OUTPUT_TSDAT2)
#define DEFAULT_DEMOD_OUTPUT_TSDAT3 (HI_UNF_TUNER_OUTPUT_TSDAT3)
#define DEFAULT_DEMOD_OUTPUT_TSDAT4 (HI_UNF_TUNER_OUTPUT_TSDAT4)
#define DEFAULT_DEMOD_OUTPUT_TSDAT5 (HI_UNF_TUNER_OUTPUT_TSDAT5)
#define DEFAULT_DEMOD_OUTPUT_TSDAT6 (HI_UNF_TUNER_OUTPUT_TSDAT6)
#define DEFAULT_DEMOD_OUTPUT_TSDAT7 (HI_UNF_TUNER_OUTPUT_TSDAT7)
#define DEFAULT_DEMOD_OUTPUT_TSSYNC (HI_UNF_TUNER_OUTPUT_TSSYNC)
#define DEFAULT_DEMOD_OUTPUT_TSVLD  (HI_UNF_TUNER_OUTPUT_TSVLD)
#define DEFAULT_DEMOD_OUTPUT_TSERR  (HI_UNF_TUNER_OUTPUT_TSERR)

/* Demux Attr */
#define DEFAULT_DEMUX_PORT          (HI_UNF_DMX_PORT_TSI_0)
#define DEFAULT_DEMUX_PORT_TYPE     (HI_UNF_DMX_PORT_TYPE_SERIAL_NOSYNC)
#define DEFAULT_DEMUX_PORT_SHARECLK (HI_UNF_DMX_PORT_TSI_0)
#define DEFAULT_DEMUX_BITSEL        (1)
#define DEFAULT_DEMUX_INCLK         (0)

/*  Cable Attr */
#define DEFAULT_CAB_DEMOD_CLK       (24000) /*KHz*/
#define DEFAULT_CAB_TS_SER_PIN      (HI_UNF_TUNER_TS_SERIAL_PIN_0)

/*  Sat Attr */
#define DEFAULT_SAT_DEMOD_CLK       (16000) /*KHz*/
#define DEFAULT_SAT_TUNER_MAXLPF    (34)    /*MHz*/
#define DEFAULT_SAT_TUNER_I2CCLK    (400)   /*KHz*/
#define DEFAULT_SAT_RF_AGC          (HI_UNF_TUNER_RFAGC_INVERT)
#define DEFAULT_SAT_IQ_SPECTRUM     (HI_UNF_TUNER_IQSPECTRUM_NORMAL)
#define DEFAULT_SAT_TS_CLK_POLAR    (HI_UNF_TUNER_TSCLK_POLAR_RISING)
#define DEFAULT_SAT_TS_FORMAT       (HI_UNF_TUNER_TS_FORMAT_TS)
#define DEFAULT_SAT_TS_SER_PIN      (HI_UNF_TUNER_TS_SERIAL_PIN_0)
#define DEFAULT_SAT_DISEQC_WAVE     (HI_UNF_TUNER_DISEQCWAVE_NORMAL)
#define DEFAULT_SAT_LNBCTRL_DEV     (HI_UNF_LNBCTRL_DEV_TYPE_MPS8125)
#define DEFAULT_SAT_LNBCTRL_DEV_ADDR (0)

/* Ter Attr */
#define DEFAULT_TER_DEMOD_CLK       (24000) /*KHz*/
#define DEFAULT_TER_TUNER_MAXLPF    (34)    /*MHz*/
#define DEFAULT_TER_TUNER_I2CCLK    (400)   /*KHz*/
#define DEFAULT_TER_RF_AGC          (HI_UNF_TUNER_RFAGC_INVERT)
#define DEFAULT_TER_IQ_SPECTRUM     (HI_UNF_TUNER_IQSPECTRUM_NORMAL)
#define DEFAULT_TER_TS_CLK_POLAR    (HI_UNF_TUNER_TSCLK_POLAR_RISING)
#define DEFAULT_TER_TS_FORMAT       (HI_UNF_TUNER_TS_FORMAT_TS)
#define DEFAULT_TER_TS_SER_PIN      (HI_UNF_TUNER_TS_SERIAL_PIN_0)
#define DEFAULT_TER_TS_SYNC_HEAD    (HI_UNF_TUNER_TS_SYNC_HEAD_AUTO)

/* TSO */
#define DEFAULT_DEMUX_TSO_NUM       (1)
/* TSO Attr */
#define DEFAULT_DEMUX_TSO_CLK       (HI_UNF_DMX_TSO_CLK_1200M)
#define DEFAULT_DEMUX_TSO_CLK_MODE  (HI_UNF_DMX_TSO_CLK_MODE_NORMAL)
#define DEFAULT_DEMUX_TSO_VLD_MODE  (HI_UNF_DMX_TSO_VALID_ACTIVE_HIGH)
#define DEFAULT_DEMUX_TSO_PORT_TYPE (HI_UNF_DMX_PORT_TYPE_SERIAL)
#define DEFAULT_DEMUX_TSO_BITSEL    (HI_UNF_DMX_TSO_SERIAL_BIT_0)


#define TUNER_USE        (0)


#ifdef __cplusplus
}
#endif
#endif

